AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Excel to JSON for Mendix

Parameters:
  SourceBucketName:
    Type: String
  DestinationBucketName:
    Type: String
Resources:
  ## SQS Queue
  ExcelProcessedQueue:
    Type: AWS::SQS::Queue
  ## S3 bucket
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref SourceBucketName    
  DestinationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DestinationBucketName   

  ## Lambda function
  XLSX2JSONMx:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: nodejs18.x
      Timeout: 600
      MemorySize: 2048
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref SourceBucketName
        - S3CrudPolicy:
            BucketName: !Ref DestinationBucketName
        - SQSSendMessagePolicy:
            QueueName: !GetAtt ExcelProcessedQueue.QueueName
      Environment:
        Variables:
          DESTINATION_BUCKETNAME: !Ref DestinationBucketName              
          SQS_QUEUE_URL: !GetAtt ExcelProcessedQueue
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref SourceBucket
            Events: s3:ObjectCreated:*
            Filter: 
              S3Key:
                Rules:
                  - Name: suffix
                    Value: '.xlsx'     
Outputs:
  SourceBucketName:
    Value: !Ref SourceBucketName
    Description: S3 Bucket for object storage
  DestinationBucketName:
    Value: !Ref DestinationBucketName
    Description: S3 destination Bucket for object storage
  FunctionArn:
    Value: !Ref XLSX2JSONMx
    Description: XLSX2JSONMx function  Arn
  SQSqueueName:
    Description: SQS queue name
    Value: !GetAtt ExcelProcessedQueue.QueueName
  SQSqueueARN:
    Description: SQS queue ARN
    Value: !GetAtt ExcelProcessedQueue.Arn
  SQSqueueURL:
    Description: SQS queue URL
    Value: !Ref ExcelProcessedQueue